### ISSUE TITLE
Patch the security issue found in the vanilla Sauerbraten client

### ISSUE THREAD

**Issue by Calinou** [extra-a/sauer-sdl2#1]
A security issue in the vanilla Sauerbraten client was found recently; see [Sauerbraten patch January 2018](http://www.sauerworld.org/sauerbraten-patch-january-2018/) for more information.

The relevant commits on Sauerbraten SVN that fix the issue are [r5379](https://sourceforge.net/p/sauerbraten/code/5379/) and [r5380](https://sourceforge.net/p/sauerbraten/code/5380/).

**Comment by extra-a** [comment]
fixed in 2.3.3
